### ISSUE TITLE
Component configuration API

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/features#297] opened 2017-05-05 03:27 UTC
# Feature Description
- One-line feature description (can be used as a release note):
Implement a config API for each kubernetes component and migrate off flag driven configuration.
- Primary contact (assignee):
@mikedanese
- Responsible SIGs: sig-cluster-lifecycle
- Design proposal link (community repo):
TBD
- Reviewer(s) - (for LGTM) recommend having 2+ reviewers (at least one from code-area OWNERS file) agreed to review. Reviewers from multiple companies preferred:
TBD
- Approver (likely from SIG/area to which feature belongs):
@roberthbailey 
- Feature target (which target equals to which milestone):
  - Alpha release target TBD
  - Beta release target TBD
  - Stable release target TBD

**Comment by roberthbailey** [comment] 2017-05-25 20:11
Dupe of #115

**Closed by roberthbailey** 2017-05-25 20:11 UTC
Labels: sig/cluster-lifecycle
